// Command cwe-catalog regenerates internal/unified/cwe/catalog_gen.go
// from the MITRE CWE catalog XML. Dev-time tool, same standing as
// tools/schema-coverage — not built into the production binary.
//
// Usage:
//
//	go run ./tools/cwe-catalog -in cwec_v4.20.xml -out internal/unified/cwe/catalog_gen.go
//
// The input XML is https://cwe.mitre.org/data/xml/cwec_latest.xml.zip
// (unzipped). Weaknesses, Categories, and Views are all included so
// every CWE-ID that upstream advisory data may reference (CNAs
// occasionally point at category IDs like CWE-310) resolves to its
// official name. Deprecated entries keep their names too — upstream
// data referencing them should still render something meaningful.
package main

import (
	"encoding/xml"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"sort"
	"strconv"
)

type catalog struct {
	Version    string `xml:"Version,attr"`
	Date       string `xml:"Date,attr"`
	Weaknesses []struct {
		ID   string `xml:"ID,attr"`
		Name string `xml:"Name,attr"`
	} `xml:"Weaknesses>Weakness"`
	Categories []struct {
		ID   string `xml:"ID,attr"`
		Name string `xml:"Name,attr"`
	} `xml:"Categories>Category"`
	Views []struct {
		ID   string `xml:"ID,attr"`
		Name string `xml:"Name,attr"`
	} `xml:"Views>View"`
}

func main() {
	in := flag.String("in", "", "path to the unzipped cwec_vX.Y.xml")
	out := flag.String("out", "internal/unified/cwe/catalog_gen.go", "output Go file")
	flag.Parse()
	if *in == "" {
		log.Fatal("cwe-catalog: -in is required")
	}

	body, err := os.ReadFile(*in)
	if err != nil {
		log.Fatalf("cwe-catalog: read %s: %v", *in, err)
	}
	var cat catalog
	if err := xml.Unmarshal(body, &cat); err != nil {
		log.Fatalf("cwe-catalog: parse %s: %v", *in, err)
	}

	names := map[int]string{}
	add := func(id, name string) {
		n, err := strconv.Atoi(id)
		if err != nil {
			log.Fatalf("cwe-catalog: non-numeric CWE ID %q", id)
		}
		if prev, dup := names[n]; dup && prev != name {
			log.Fatalf("cwe-catalog: CWE-%d has two names: %q / %q", n, prev, name)
		}
		names[n] = name
	}
	for _, w := range cat.Weaknesses {
		add(w.ID, w.Name)
	}
	for _, c := range cat.Categories {
		add(c.ID, c.Name)
	}
	for _, v := range cat.Views {
		add(v.ID, v.Name)
	}
	if len(names) == 0 {
		log.Fatal("cwe-catalog: no entries parsed — wrong input file?")
	}

	ids := make([]int, 0, len(names))
	for id := range names {
		ids = append(ids, id)
	}
	sort.Ints(ids)

	var buf []byte
	appendf := func(format string, a ...any) {
		buf = append(buf, fmt.Sprintf(format, a...)...)
	}
	appendf("// Code generated by tools/cwe-catalog from the MITRE CWE catalog; DO NOT EDIT.\n")
	appendf("//\n// Source: https://cwe.mitre.org/data/xml/cwec_latest.xml.zip\n")
	appendf("// CWE is a trademark of The MITRE Corporation.\n\npackage cwe\n\n")
	appendf("// CatalogVersion is the MITRE CWE catalog release this table was\n// generated from.\n")
	appendf("const CatalogVersion = %q // released %s\n\n", cat.Version, cat.Date)
	appendf("var names = map[string]string{\n")
	for _, id := range ids {
		appendf("\t%q: %q,\n", fmt.Sprintf("CWE-%d", id), names[id])
	}
	appendf("}\n")

	formatted, err := format.Source(buf)
	if err != nil {
		log.Fatalf("cwe-catalog: gofmt output: %v", err)
	}
	if err := os.WriteFile(*out, formatted, 0o644); err != nil {
		log.Fatalf("cwe-catalog: write %s: %v", *out, err)
	}
	fmt.Printf("wrote %s: %d entries (catalog v%s, %s)\n", *out, len(names), cat.Version, cat.Date)
}
