#!/usr/bin/env bash
#
# scripts/setup.sh — install local development tooling.
#
# Installs:
#   - golangci-lint (pinned version) into $(go env GOPATH)/bin, built from
#     source with the local Go toolchain so the linter and the project share
#     one Go version (avoids the toolchain mismatch in #36)
#   - .git/hooks/pre-commit that runs `make lint`

set -euo pipefail

GOLANGCI_LINT_VERSION="${GOLANGCI_LINT_VERSION:-v2.11.4}"

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${repo_root}"

if ! command -v go >/dev/null 2>&1; then
  echo "error: 'go' is not installed or not on PATH" >&2
  exit 1
fi

gobin="$(go env GOPATH)/bin"
mkdir -p "${gobin}"

install_golangci_lint() {
  local target="${gobin}/golangci-lint"
  if [[ -x "${target}" ]]; then
    local current
    current="$("${target}" --version 2>/dev/null | awk '{print $4}' || true)"
    if [[ "${current}" == "${GOLANGCI_LINT_VERSION#v}" ]]; then
      echo "golangci-lint ${GOLANGCI_LINT_VERSION} is already installed at ${target}"
      return
    fi
  fi
  echo "Installing golangci-lint ${GOLANGCI_LINT_VERSION} into ${gobin} via 'go install'"
  GOBIN="${gobin}" go install \
    "github.com/golangci/golangci-lint/v2/cmd/golangci-lint@${GOLANGCI_LINT_VERSION}"
}

install_pre_commit_hook() {
  local hook_dir hook_path
  hook_dir="$(git rev-parse --git-path hooks)"
  hook_path="${hook_dir}/pre-commit"
  mkdir -p "${hook_dir}"

  cat >"${hook_path}" <<'HOOK'
#!/usr/bin/env bash
# Auto-generated by scripts/setup.sh — runs lint before each commit.
set -euo pipefail
repo_root="$(git rev-parse --show-toplevel)"
cd "${repo_root}"
exec make lint
HOOK
  chmod +x "${hook_path}"
  echo "Installed pre-commit hook at ${hook_path}"
}

install_golangci_lint
install_pre_commit_hook

echo "Setup complete."
